### ISSUE TITLE
Feature Request: make `yarn` optional

### ISSUE THREAD

**Issue by the-reality-engineer** [zposten/unorepo#7]
Looks like a great tool, would be nice if this was built into `lerna`. Would it be possible to make the `yarn` dependency optional, and just rely on `npm`?

**Comment by 0livare** [comment]
Hi @speigg,

Yes, that could definitely be done.   We could even pull the `npmConfiguration` from the user's `lerna.json` file.

But currently removing yarn would make the `uno dependencies` command not work, as it depends on yarn workspaces, and npm does not provide an equivalent feature.  This would also prevent future features from being added to unorepo that rely on yarn workspaces.  That's part of the reason that I've described unorepo as "a tool for managing a monorepo via Lerna and Yarn workspaces".

I do see benefit in making `yarn` optional, and I believe it is technically feasible.  But I feel that doing so goes against the original purpose of unorepo, and so I am hesitant to do so.
